# Generated by Django 5.2.3 on 2025-07-01 17:09

import django.db.models.deletion
import django.utils.timezone
import ts_company.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lot', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('OUVERT', 'Ouvert'), ('FERME', 'Fermé/Expédié')], default='OUVERT', max_length=20)),
                ('agent_createur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots_crees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Colis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('poids', models.DecimalField(decimal_places=2, help_text='Poids en kg', max_digits=10)),
                ('longueur', models.DecimalField(decimal_places=2, help_text='Longueur en cm', max_digits=10)),
                ('largeur', models.DecimalField(decimal_places=2, help_text='Largeur en cm', max_digits=10)),
                ('hauteur', models.DecimalField(decimal_places=2, help_text='Hauteur en cm', max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to=ts_company.models.get_upload_path)),
                ('status', models.CharField(choices=[('EN_ATTENTE_CHINE', 'En attente en Chine'), ('EN_TRANSIT', 'En transit'), ('ARRIVE_MALI', 'Arrivé au Mali'), ('RECEPTIONNE', 'Réceptionné')], default='EN_ATTENTE_CHINE', max_length=20)),
                ('shipping_method', models.CharField(choices=[('AERIEN', 'Aérien'), ('MARITIME', 'Maritime')], max_length=10)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_arrivee', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colis', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colis', to='ts_company.lot')),
            ],
        ),
    ]
