# Generated by Django 5.2.3 on 2025-07-02 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts_company', '0002_shippingprice_colis_estimated_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingprice',
            name='price_per_kg',
        ),
        migrations.AddField(
            model_name='shippingprice',
            name='price_unit',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Prix par unité (Kg ou M³) en F CFA', max_digits=10),
        ),
        migrations.AddField(
            model_name='shippingprice',
            name='unit_type',
            field=models.CharField(choices=[('KG', 'Kilogramme'), ('M3', 'Mètre Cube')], default='KG', max_length=2),
        ),
        migrations.AlterField(
            model_name='shippingprice',
            name='min_charge_weight',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text="Poids/Volume minimum pour le calcul à l'unité", max_digits=10),
        ),
    ]
