# Generated by Django 5.2.3 on 2025-07-02 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts_company', '0003_remove_shippingprice_price_per_kg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colis',
            name='hauteur',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Hauteur en cm', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='colis',
            name='largeur',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Largeur en cm', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='colis',
            name='longueur',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Longueur en cm', max_digits=10, null=True),
        ),
    ]
