# Generated by Django 5.2.3 on 2025-07-02 03:10

from django.db import migrations
from django.utils import timezone

def add_default_lot(apps, schema_editor):
    Colis = apps.get_model('ts_company', 'Colis')
    Lot = apps.get_model('ts_company', 'Lot')
    CustomUser = apps.get_model('authentication', 'CustomUser')

    # Find an existing ADMIN user or create one if none exists
    try:
        admin_user = CustomUser.objects.filter(role='ADMIN').first()
        if not admin_user:
            # Fallback: create a dummy admin user if no admin exists
            admin_user = CustomUser.objects.create_user(
                phone_number='0000000000', 
                password='defaultadmin', 
                first_name='Default', 
                last_name='Admin', 
                role='ADMIN',
                is_staff=True,
                is_superuser=True
            )
    except Exception:
        # Handle cases where CustomUser might not be fully set up yet
        admin_user = None

    if admin_user:
        default_lot, created = Lot.objects.get_or_create(
            numero_lot='DEFAULT_LOT',
            defaults={
                'agent_createur': admin_user,
                'date_creation': timezone.now(),
                'status': 'OUVERT'
            }
        )
        # Update existing Colis instances that have a null lot
        Colis.objects.filter(lot__isnull=True).update(lot=default_lot)

class Migration(migrations.Migration):

    dependencies = [
        ('ts_company', '0004_alter_colis_hauteur_alter_colis_largeur_and_more'),
        ('authentication', '0004_alter_customuser_role'), # Add dependency on CustomUser migration
    ]

    operations = [
        migrations.RunPython(add_default_lot, migrations.RunPython.noop),
    ]