# Generated by Django 5.2.3 on 2025-07-02 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts_company', '0005_add_default_lot_to_colis'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='date_expedition',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='colis',
            name='lot',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.PROTECT, related_name='colis', to='ts_company.lot'),
            preserve_default=False,
        ),
    ]
