# Generated by Django 5.2.3 on 2025-07-02 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts_company', '0006_lot_date_expedition_alter_colis_lot'),
    ]

    operations = [
        migrations.AddField(
            model_name='colis',
            name='delivery_address',
            field=models.TextField(blank=True, help_text='Adresse de livraison spécifique pour ce colis', null=True),
        ),
    ]
