# Generated by Django 5.2.3 on 2025-07-05 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts_company', '0008_colis_notification_lot_closed_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colis',
            name='notified_client',
            field=models.BooleanField(default=False),
        ),
    ]
