# Generated by Django 5.2.3 on 2025-07-02 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_otp_code_customuser_otp_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('AGENT', 'Agent'), ('AGENT_CHINE', 'Agent Chine'), ('AGENT_MALI', 'Agent Mali'), ('CLIENT', 'Client')], default='CLIENT', max_length=15),
        ),
    ]
