# Generated by Django 5.2.3 on 2025-07-02 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('AGENT_CHINE', 'Agent Chine'), ('AGENT_MALI', 'Agent Mali'), ('CLIENT', 'Client')], default='CLIENT', max_length=15),
        ),
    ]
